export const typography = {
  'type-header-h1': {
    className: 'type-header-h1',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: 'var(--responsive-font-headings-h1-text-size)',
    lineHeight: 'var(--responsive-font-headings-h1-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-header-h2': {
    className: 'type-header-h2',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: 'var(--responsive-font-headings-h2-text-size)',
    lineHeight: 'var(--responsive-font-headings-h2-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-header-h3': {
    className: 'type-header-h3',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: 'var(--responsive-font-headings-h3-text-size)',
    lineHeight: 'var(--responsive-font-headings-h3-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-header-h4': {
    className: 'type-header-h4',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: 'var(--responsive-font-headings-h4-text-size)',
    lineHeight: 'var(--responsive-font-headings-h4-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-header-h5': {
    className: 'type-header-h5',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: 'var(--responsive-font-headings-h5-text-size)',
    lineHeight: 'var(--responsive-font-headings-h5-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-header-h6': {
    className: 'type-header-h6',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: 'var(--responsive-font-headings-h6-text-size)',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-lg': {
    className: 'type-body-lg',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-lg-medium': {
    className: 'type-body-lg-medium',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 500,
    fontSize: '20px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-lg-semibold': {
    className: 'type-body-lg-semibold',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-lg-link': {
    className: 'type-body-lg-link',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'underline' as const,
  },
  'type-body-m': {
    className: 'type-body-m',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-m-medium': {
    className: 'type-body-m-medium',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-m-semibold': {
    className: 'type-body-m-semibold',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-m-link': {
    className: 'type-body-m-link',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: 'var(--responsive-font-headings-h6-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'underline' as const,
  },
  'type-body-sm': {
    className: 'type-body-sm',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: 'var(--responsive-font-copy-body-sm-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-sm-medium': {
    className: 'type-body-sm-medium',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: 'var(--responsive-font-copy-body-sm-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-sm-semibold': {
    className: 'type-body-sm-semibold',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: 'var(--responsive-font-copy-body-sm-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-sm-link': {
    className: 'type-body-sm-link',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: 'var(--responsive-font-copy-body-sm-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'underline' as const,
  },
  'type-body-caption': {
    className: 'type-body-caption',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: 'var(--responsive-font-copy-caption-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-caption-medium': {
    className: 'type-body-caption-medium',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: 'var(--responsive-font-copy-caption-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-caption-semibold': {
    className: 'type-body-caption-semibold',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: 'var(--responsive-font-copy-caption-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'none' as const,
  },
  'type-body-caption-link': {
    className: 'type-body-caption-link',
    fontFamily: 'var(--font-family-primary)',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: 'var(--responsive-font-copy-caption-line-height)',
    letterSpacing: '0',
    textTransform: 'none' as const,
    textDecoration: 'underline' as const,
  },
} as const

export type Typography = typeof typography
